name: Release App
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Node 20 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./NODE/node_twenty.sh
          dockerfile-path: ./NODE/
          build-command: docker build --build-arg NODE_MAJOR_VERSION="20"
      - name: Test Node 18 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./NODE/node_eighteen.sh
          dockerfile-path: ./NODE/
          build-command: docker build --build-arg NODE_MAJOR_VERSION="18"
      - name: Test ASPNET 6 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./ASPNET_6/aspnet_six.sh
          dockerfile-path: ./ASPNET_6/
      - name: Test .NET SDK 6 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./DOTNET_SDK_6/dotnet_sdk_six.sh
          dockerfile-path: ./DOTNET_SDK_6/
  release:
    runs-on: ubuntu-latest
    name: Release Images
    needs: test
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ vars.DOCKER_TOKEN }}
      NODE_IMAGE_NAME: ${{ vars.NODE_IMAGE_NAME }}
      ASPNET_IMAGE_NAME: ${{ vars.ASPNET_IMAGE_NAME }}
      DOTNET_SDK_IMAGE_NAME: ${{ vars.DOTNET_SDK_IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Publish Release
        uses: outoforbitdev/action-semantic-release@v1.4.3-staging.2
        id: semantic-release
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          skip-changelog: ${{ github.ref_name != 'main' }}
      - name: Summarize Versions
        env:
          LAST_VERSION: ${{ steps.semantic-release.outputs.last-version }}
          NEXT_VERSION: ${{ steps.semantic-release.outputs.next-version }}
          VERSION_RELEASED: >-
            ${{ steps.semantic-release.outputs.version-released}}
        run: >-
          echo "### Version Summaries" >> $GITHUB_STEP_SUMMARY;
          echo "* Last version - $LAST_VERSION" >> $GITHUB_STEP_SUMMARY;
          echo "* Next version - $NEXT_VERSION" >> $GITHUB_STEP_SUMMARY;
          echo "* Version released - $VERSION_RELEASED" >> $GITHUB_STEP_SUMMARY
      - name: Publish Node 20 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ env.DOCKER_USERNAME }}
          docker-token: ${{ env.DOCKER_TOKEN }}
          image-name: ${{ env.NODE_IMAGE_NAME }}
          dockerfile-path: ./NODE/
          image-tag: "node20-${{ steps.semantic-release.outputs.next-version }}"
      - name: Publish Node 18 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ env.DOCKER_USERNAME }}
          docker-token: ${{ env.DOCKER_TOKEN }}
          image-name: ${{ env.NODE_IMAGE_NAME }}
          dockerfile-path: ./NODE/
          image-tag: "node18-${{ steps.semantic-release.outputs.next-version }}"
      - name: Publish ASPNET 6 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ env.DOCKER_USERNAME }}
          docker-token: ${{ env.DOCKER_TOKEN }}
          image-name: ${{ env.ASPNET_IMAGE_NAME }}
          dockerfile-path: ./ASPNET_6/
          image-tag: "aspnet6-${{ steps.semantic-release.outputs.next-version }}"
      - name: Publish .NET SDK 6 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ env.DOCKER_USERNAME }}
          docker-token: ${{ env.DOCKER_TOKEN }}
          image-name: ${{ env.DOTNET_SDK_IMAGE_NAME }}
          image-tag: "sdk6-${{ steps.semantic-release.outputs.next-version }}"
          dockerfile-path: ./DOTNET_SDK_6/
