name: Test App
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Node 20 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./NODE/node_twenty.sh
          dockerfile-path: ./NODE/
          build-command: docker build --build-arg NODE_MAJOR_VERSION="20"
      - name: Test Node 18 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./NODE/node_eighteen.sh
          dockerfile-path: ./NODE/
          build-command: docker build --build-arg NODE_MAJOR_VERSION="18"
      - name: Test ASPNET 6 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./ASPNET_6/aspnet_six.sh
          dockerfile-path: ./ASPNET_6/
      - name: Test .NET SDK 6 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./DOTNET_SDK_6/dotnet_sdk_six.sh
          dockerfile-path: ./DOTNET_SDK_6/
      - name: Set Example Release
        id: semantic-release
        run: echo "next-version=test-tag" >> "$GITHUB_OUTPUT"; echo "version-released=true" >> "$GITHUB_OUTPUT"
      - name: Publish Node 20 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.NODE_IMAGE_NAME }}
          image-tag: "node20-${{ steps.semantic-release.outputs.next-version }}"
      - name: Publish Node 18 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.NODE_IMAGE_NAME }}
          image-tag: "node18-${{ steps.semantic-release.outputs.next-version }}"
      - name: Publish ASPNET 6 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.ASPNET_IMAGE_NAME }}
          image-tag: "aspnet6-${{ steps.semantic-release.outputs.next-version }}"
      - name: Publish .NET SDK 6 Image
        uses: outoforbitdev/action-docker-publish@v2.1.0-staging.1
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.ASPNET_IMAGE_NAME }}
          image-tag: "sdk6-${{ steps.semantic-release.outputs.next-version }}"
