name: Test App
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test-node:
    runs-on: ubuntu-latest
    name: Test Node Images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Node 20 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./NODE/node_twenty.sh
          dockerfile-path: ./NODE/
          build-command: docker build --build-arg NODE_MAJOR_VERSION="20"
      - name: Test Node 18 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./NODE/node_eighteen.sh
          dockerfile-path: ./NODE/
          build-command: docker build --build-arg NODE_MAJOR_VERSION="18"
  test-aspnet:
    runs-on: ubuntu-latest
    name: Test ASPNET Images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test ASPNET 6 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./ASPNET_6/aspnet_six.sh
          dockerfile-path: ./ASPNET_6/
  test-dotnet-sdk:
    runs-on: ubuntu-latest
    name: Test .NET SDK Images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test .NET SDK 6 Image
        uses: outoforbitdev/action-docker-test@v0.0.2-staging.2
        with:
          test-command: sh ./DOTNET_SDK_6/dotnet_sdk_six.sh
          dockerfile-path: ./DOTNET_SDK_6/
